### PR TITLE
chore(gauge_chart_plugin): upgrade to SDK 9

### PR DESCRIPTION
**Pull request by dremileta**

### CODE REVIEW

**Comment by kazakovkirilliy** [comment]
Please, keep only one lock file - `package-lock.json` (as it is generated initially by the [Plugin Toolkit](https://sdk.gooddata.com/gooddata-ui/docs/dashboard_plugins.html#getting-started))

**Comment by kazakovkirilliy** [comment]
I would consider renaming component folder into components to retain consistence across plugins

**Comment by dremileta** [comment]
> I would consider renaming component folder into components to retain consistency across plugins

@kazakovkirilliy I was looking at [dashboard_description_plugin](https://github.com/gooddata/gooddata-dashboard-plugins/tree/master/dashboard_description_plugin) while doing upgrade. So I did keep it consistent :)

**Comment by davidzoufaly** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-dashboard-plugins-gate-PR42

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-sonarqube-scan-zuul-gate/44/ : SUCCESS in 35s
- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-fossa-scanning-zuul/21/ : SUCCESS in 2m 16s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-merge-compliance-check/45/ : SUCCESS in 9s

**Pull request merged**
