### PR TITLE
chore(common-utils): remove common-utils folder

### PR DESCRIPTION
**Pull request by kazakovkirilliy**
Each plugin will now have its own utils folder

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by dremileta — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-dashboard-plugins-gate-PR67

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-sonarqube-scan-zuul-gate/60/ : SUCCESS in 56s
- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-fossa-scanning-zuul/37/ : SUCCESS in 46s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-merge-compliance-check/61/ : SUCCESS in 9s

**Pull request merged**
