### PR TITLE
chore(radial_bar_chart_plugin): update GoodData SDK to v9.6.0

### PR DESCRIPTION
**Pull request by kazakovkirilliy**
Update Dashboard plugin to GoodData SDK v9.6.0. More information about the new SDK version can be found in [GoodData docs](https://www.gooddata.com/docs/gooddata-ui/latest/references/dashboard_component/dashboard_plugins/)

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by dremileta — APPROVED** [review]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-dashboard-plugins-gate-PR62

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-sonarqube-scan-zuul-gate/55/ : SUCCESS in 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-fossa-scanning-zuul/32/ : SUCCESS in 51s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-merge-compliance-check/56/ : SUCCESS in 9s

**Pull request merged**
