### PR TITLE
chore(dashboard-description-plugin): update GoodData SDK to v9.6.0

### PR DESCRIPTION
**Pull request by kazakovkirilliy**
Update Dashboard plugin to GoodData SDK v9.6.0. More information about the new SDK version can be found in [GoodData docs](https://www.gooddata.com/docs/gooddata-ui/latest/references/dashboard_component/dashboard_plugins/)

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Review by dremileta — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-dashboard-plugins-gate-PR66

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Pull request merged**
