### PR TITLE
chore(sankey_dependency_wheel_plugin): sdk update to 9.4

### PR DESCRIPTION
**Pull request by dremileta**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by davidzoufaly** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-dashboard-plugins-gate-PR53

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-sonarqube-scan-zuul-gate/50/ : SUCCESS in 58s
- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-fossa-scanning-zuul/27/ : SUCCESS in 48s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-merge-compliance-check/51/ : SUCCESS in 9s

**Pull request merged**
