### PR TITLE
chore(radial_bar_chart_plugin): upgrade to SDK 9

### PR DESCRIPTION
**Pull request by dremileta**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by kazakovkirilliy** [comment]
I would consider renaming `component` folder into `components` to retain consistence across plugins

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by davidzoufaly** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-dashboard-plugins-gate-PR44

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-sonarqube-scan-zuul-gate/42/ : SUCCESS in 32s
- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-fossa-scanning-zuul/19/ : SUCCESS in 1m 59s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-merge-compliance-check/43/ : SUCCESS in 10s

**Pull request merged**
