### PR TITLE
chore(polar_area_chart): add data-testid attribute

### PR DESCRIPTION
**Pull request by kazakovkirilliy**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

**Comment by davidzoufaly** [comment]
LGTM

**Comment by yenkins** [comment]
### Sonar scan result


More detail, see in https://sonarqube-gate.intgdc.com/dashboard?id=gooddata-dashboard-plugins-gate-PR71

To scan for vulnerabilities in dependencies and run unit tests (to get coverage report in sonar) please comment your PR with 'extended check sonar'.

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-sonarqube-scan-zuul-gate/64/ : SUCCESS in 1m 02s
- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-fossa-scanning-zuul/41/ : SUCCESS in 1m 24s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-dashboard-plugins-merge-compliance-check/65/ : SUCCESS in 6s

**Pull request merged**
